/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package amazon;

import amazon.exceptions.NoFormatSelectedException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Francesco
 */
public class FinestraCorriere extends EditForm {

    /**
     * Creates new form FinestraUtente
     * @param parent
     * @param modal
     */
    public FinestraCorriere(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public int corriereID;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tCorriere_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tCorriere_Nome = new javax.swing.JTextField();
        bEsc = new javax.swing.JButton();
        bOk = new javax.swing.JButton();
        cRap = new javax.swing.JCheckBox();
        cMed = new javax.swing.JCheckBox();
        cStand = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifica Autore");

        jLabel1.setText("Corriere_ID");

        tCorriere_ID.setEnabled(false);

        jLabel2.setText("Nome Corrieri");

        tCorriere_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCorriere_NomeActionPerformed(evt);
            }
        });

        bEsc.setText("Annulla");
        bEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEscActionPerformed(evt);
            }
        });

        bOk.setText("OK");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        cRap.setText("1 Giorno");
        cRap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cRapActionPerformed(evt);
            }
        });

        cMed.setText("2-3 Giorni");
        cMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMedActionPerformed(evt);
            }
        });

        cStand.setText("3-5 Giorni");
        cStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cStandActionPerformed(evt);
            }
        });

        jLabel3.setText("Modalità di Spedizione a disposizione");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEsc))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tCorriere_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tCorriere_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cRap)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cMed)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cStand))
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tCorriere_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tCorriere_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cRap)
                    .addComponent(cMed)
                    .addComponent(cStand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEsc)
                    .addComponent(bOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        eseguiOk();
    }//GEN-LAST:event_bOkActionPerformed

    private void bEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEscActionPerformed
        chiudiFinestra();
    }//GEN-LAST:event_bEscActionPerformed

    private void tCorriere_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCorriere_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCorriere_NomeActionPerformed

    private void cRapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cRapActionPerformed

    }//GEN-LAST:event_cRapActionPerformed

    private void cStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cStandActionPerformed

    }//GEN-LAST:event_cStandActionPerformed

    private void cMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMedActionPerformed

    }//GEN-LAST:event_cMedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEsc;
    private javax.swing.JButton bOk;
    private javax.swing.JCheckBox cMed;
    private javax.swing.JCheckBox cRap;
    private javax.swing.JCheckBox cStand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tCorriere_ID;
    private javax.swing.JTextField tCorriere_Nome;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void fillContents() {
        inizializzaCheckBox();
        try {
            tCorriere_ID.setText((String)dati.get(0));
            tCorriere_Nome.setText((String)dati.get(1));
            corriereID = Integer.parseInt((String)dati.get(0));
            
            ResultSet spedizioni = DBConnection.visualizzaModSpedizione(corriereID);
            while(spedizioni.next())    {
                if (spedizioni.getInt(1) == 8)  {
                    cRap.setSelected(true);
                }
                if (spedizioni.getInt(1) == 4)  {
                    cMed.setSelected(true);
                }
                if (spedizioni.getInt(1) == 0)  {
                    cStand.setSelected(true);
                }
            }
        } catch (SQLException ex) {
            mostraErrore(ex);
        }
    }
    
    private void inizializzaCheckBox() {
        cRap.setSelected(false);
        cMed.setSelected(false);
        cStand.setSelected(false);
    }

    @Override
    protected void cleanContents() {
        inizializzaCheckBox();
        tCorriere_ID.setText("");
        tCorriere_Nome.setText("");
    }
    
    private void eseguiOk()
    {
        
        try {
            tuttiDisattivati();
            setVisible(false);
            if (mode == ADDN)   {
                corriereID = DBConnection.creaCorriere(tCorriere_Nome.getText());
                
            }
            else {
                corriereID = Integer.parseInt(tCorriere_ID.getText());
                DBConnection.aggiornaCorriere(corriereID, tCorriere_Nome.getText());
            }
            DBConnection.applicaModSpedizione(corriereID, cRap.isSelected(), cMed.isSelected(), cStand.isSelected());
            chiudiFinestra();
        }
        catch(SQLException ex){
            mostraErrore(ex);
            setVisible(true);
        } catch (NoFormatSelectedException ex) {
            JOptionPane.showMessageDialog(this, "Devi selezionare almeno un formato", "Errore!", JOptionPane.ERROR_MESSAGE, null);
        }
    }
        
    /**
     * Lancia eccezione se non sono stati selezionati dei tipi di spedizione.
     * @throws NoFormatSelectedException 
     */
    private void tuttiDisattivati() throws NoFormatSelectedException {
        if (!cRap.isSelected() && !cMed.isSelected() && !cStand.isSelected())
            throw new NoFormatSelectedException();
    }
    
    @Override
    protected String titoloNuovo () {
        return "Nuovo Corriere";
    }
    
    @Override
    protected String titoloModifica () {
        return "Modifica Corriere";
    }
}
