/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package amazon;

/**
 *
 * @author pixel89
 */
import static amazon.DBConnection.verificaSconto;
import amazon.exceptions.CodeAlreadyUsedException;
import amazon.exceptions.CodeNotValidException;
import amazon.exceptions.TooMuchDealsException;
import amazon.modelliTabelle.DBTableModel;
import amazon.modelliTabelle.ScontiModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;

public class FinestraInfoUtente extends javax.swing.JDialog {

    /**
     * Creates new form FinestraInfoUtente
     */
    public FinestraInfoUtente(java.awt.Frame parent, boolean modal, int idUtente) {
        super(parent, modal);
        //this.idUtente=idUtente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ID = new javax.swing.JLabel();
        jLabel_textID = new javax.swing.JLabel();
        jLabel_textNome = new javax.swing.JLabel();
        jLabel_Nome = new javax.swing.JLabel();
        jLabel_textCognome = new javax.swing.JLabel();
        jLabel_Cognome = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_textEmail = new javax.swing.JLabel();
        jLabel_textPassword = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jLabel_Telefono = new javax.swing.JLabel();
        jLabel_textTelefono = new javax.swing.JLabel();
        jButton_Carrello = new javax.swing.JButton();
        jButton_ListaDesideri = new javax.swing.JButton();
        jButton_StoricoOrdini = new javax.swing.JButton();
        jButton_Chiudi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_ID.setText("ID");

        jLabel_textID.setText("jLabel_textID");

        jLabel_textNome.setText("jLabel_textNome");

        jLabel_Nome.setText("Nome");

        jLabel_textCognome.setText("jLabel_textCognome");

        jLabel_Cognome.setText("Cognome");

        jLabel_Email.setText("Email");

        jLabel_textEmail.setText("jLabel_textEmail");

        jLabel_textPassword.setText("jLabel_textPassword");

        jLabel_Password.setText("Password");

        jLabel_Telefono.setText("Telefono");

        jLabel_textTelefono.setText("jLabel_textTelefono");

        jButton_Carrello.setText("Visualizza Carrello");
        jButton_Carrello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CarrelloActionPerformed(evt);
            }
        });

        jButton_ListaDesideri.setText("Visualizza Lista Desideri");

        jButton_StoricoOrdini.setText("Visualizza Storico Ordini");
        jButton_StoricoOrdini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StoricoOrdiniActionPerformed(evt);
            }
        });

        jButton_Chiudi.setText("Chiudi");
        jButton_Chiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChiudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel_ID)
                                .addGap(64, 64, 64))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Nome)
                                .addGap(41, 41, 41)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_textNome)
                            .addComponent(jLabel_textID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Password)
                            .addComponent(jLabel_Telefono))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_textPassword)
                            .addComponent(jLabel_textTelefono)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel_Cognome)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Email)
                                .addGap(44, 44, 44)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_textEmail)
                            .addComponent(jLabel_textCognome))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_ListaDesideri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Carrello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_StoricoOrdini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Chiudi)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ID)
                            .addComponent(jLabel_textID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Nome)
                            .addComponent(jLabel_textNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Cognome)
                            .addComponent(jLabel_textCognome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Email)
                            .addComponent(jLabel_textEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Password)
                            .addComponent(jLabel_textPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Telefono)
                            .addComponent(jLabel_textTelefono)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Carrello)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ListaDesideri)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_StoricoOrdini)))
                .addGap(18, 18, 18)
                .addComponent(jButton_Chiudi)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_StoricoOrdiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StoricoOrdiniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_StoricoOrdiniActionPerformed

    private void jButton_ChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChiudiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ChiudiActionPerformed

    private void jButton_CarrelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CarrelloActionPerformed
        //FinestraOrdine finestra = new FinestraOrdine(this, false, idUtente);
        //finestra.setVisible(true);
    }//GEN-LAST:event_jButton_CarrelloActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Carrello;
    private javax.swing.JButton jButton_Chiudi;
    private javax.swing.JButton jButton_ListaDesideri;
    private javax.swing.JButton jButton_StoricoOrdini;
    private javax.swing.JLabel jLabel_Cognome;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Telefono;
    private javax.swing.JLabel jLabel_textCognome;
    private javax.swing.JLabel jLabel_textEmail;
    private javax.swing.JLabel jLabel_textID;
    private javax.swing.JLabel jLabel_textNome;
    private javax.swing.JLabel jLabel_textPassword;
    private javax.swing.JLabel jLabel_textTelefono;
    // End of variables declaration//GEN-END:variables
}
