/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package amazon;

import amazon.utility.BoxUtility;
import amazon.utility.Contatto;
import java.awt.*;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.*;

/**
 *
 * @author Francesco
 */
public class FinestraModificaMetodoPagamento extends EditForm {

    /**
     * Creazione della finestra
     * @param parent finestra chiamante
     * @param modal true per bloccare il genitore
     * @param utenteID id dell'utente
     */
    public FinestraModificaMetodoPagamento(java.awt.Dialog parent, boolean modal, int utenteID) {
        super(parent, modal);
        initComponents();
        genitore = (FinestraModPagamento)parent;
        this.utenteID = utenteID;
    }
    
    private int pagamentoID;
    private final int utenteID;
    private String oldNum;
    private FinestraModPagamento genitore;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNumero = new javax.swing.JTextField();
        tCiv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tMese = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tAnno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cContatto = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        tCognome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tCarta = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiungi Metodo di Pagamento");
        setMinimumSize(new java.awt.Dimension(470, 310));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Numero Carta di Credito");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CIV");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Data di Scadenza");

        tNumero.setToolTipText("Inserire il codice della carta di credito.");

        jLabel4.setText("mm");

        jLabel5.setText("aaaa");

        jLabel6.setText("Indirizzo di Fatturazione");

        cContatto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cContatto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cContattoActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Nome Titolare Carta");

        jLabel8.setText("Codice di Sicurezza a 3 cifre");

        jLabel9.setText("Tipo Carta");

        jButton1.setText("Annulla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tCarta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Cognome Titolare Carta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tCiv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tMese, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addComponent(tAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cContatto, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cContatto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tMese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tCiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        eseguiOk();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        chiudiFinestra();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cContattoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cContattoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cContattoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cContatto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tAnno;
    private javax.swing.JComboBox tCarta;
    private javax.swing.JTextField tCiv;
    private javax.swing.JTextField tCognome;
    private javax.swing.JTextField tMese;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tNumero;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void fillContents() {
        pagamentoID = Integer.parseInt(dati.get(1).toString());
        BoxUtility.impostaTipoCarta(tCarta, dati.get(5).toString());
        oldNum = dati.get(2).toString();
        tNumero.setText(oldNum);
        tCiv.setText(dati.get(7).toString());
        tMese.setText(getMese(dati.get(6).toString()));
        tAnno.setText(getAnno(dati.get(6).toString()));
        tNome.setText(dati.get(3).toString());
        tCognome.setText(dati.get(4).toString());
        try {
            impostaComboBox(Integer.parseInt(dati.get(0).toString()));
        } catch (SQLException ex) {
            mostraErrore(ex);
        }
    }

    @Override
    protected void cleanContents() {
        BoxUtility.impostaTipoCarta(tCarta);
        tNumero.setDocument(new JTextFieldLimit(16));
        tCiv.setDocument(new JTextFieldLimit(3));
        tMese.setDocument(new JTextFieldLimit(2));
        tAnno.setDocument(new JTextFieldLimit(4));
        tNome.setText("");
        tCognome.setText("");
        try {
            impostaComboBox();
        } catch (SQLException ex) {
            mostraErrore(ex);
        }
    }

    @Override
    protected String titoloNuovo() {
        return "Nuovo metodo di pagamento";
    }

    @Override
    protected String titoloModifica() {
        return "Modifica metodo di pagamento";
    }
    
    private String getMese(String data) {
        return data.substring(5, 7);
    }
    
    private String getAnno(String data) {
        return data.substring(0, 4);
    }
    
    private void impostaComboBox() throws SQLException {
        BoxUtility.impostaPerIndirizzi(cContatto, utenteID);
    }
    
    private void impostaComboBox(int idContatto) throws SQLException {
        impostaComboBox();
        BoxUtility.setIndirizzoId(cContatto, idContatto);
    }
    
    private void eseguiOk() {
        setVisible(false);
        try {
            if (mode == ADDN)
                DBConnection.creaModPagamento(BoxUtility.getIndirizzoId(cContatto),
                        tNumero.getText(), tNome.getText(), tCognome.getText(),
                        BoxUtility.getTipoCarta(tCarta), getScadenza(),
                        Integer.parseInt(tCiv.getText()));
            else
                DBConnection.aggiornaModPagamento(pagamentoID,
                        BoxUtility.getIndirizzoId(cContatto),
                        tNumero.getText(), tNome.getText(), tCognome.getText(),
                        BoxUtility.getTipoCarta(tCarta), getScadenza(),
                        Integer.parseInt(tCiv.getText()));
            genitore.aggiornaTabella();
            chiudiFinestra();
        } catch (SQLException ex) {
            mostraErrore(ex);
            setVisible(true);
        }
    }
    
    private String getScadenza() {
        String mese = tMese.getText();
        String anno = tAnno.getText();
        return anno+"-"+mese+"01";
    }
    
}
